Internal Server Error: /api/goal/
Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 81, in save
    self.full_clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\base.py", line 1626, in full_clean
    self.clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 60, in clean
    if self.target_emissions > (self.start_emissions * 0.8):
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\views.py", line 114, in create
    self.perform_create(serializer)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\serializers.py", line 42, in create
    return super().create(validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 1008, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Goal.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Goal.objects.create()`. You may need to make the field read-only, or override the GoalSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 81, in save
    self.full_clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\base.py", line 1626, in full_clean
    self.clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 60, in clean
    if self.target_emissions > (self.start_emissions * 0.8):
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

"POST /api/goal/ HTTP/1.1" 500 166589
Internal Server Error: /api/goal/
Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 81, in save
    self.full_clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\base.py", line 1626, in full_clean
    self.clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 60, in clean
    if self.target_emissions > (self.start_emissions * 0.8):
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\views.py", line 114, in create
    self.perform_create(serializer)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\serializers.py", line 42, in create
    return super().create(validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 1008, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Goal.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Goal.objects.create()`. You may need to make the field read-only, or override the GoalSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 81, in save
    self.full_clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\env\lib\site-packages\django\db\models\base.py", line 1626, in full_clean
    self.clean()
  File "C:\FH JOANNEUM\Semester_5\co2champion_wapdev2\co2champion\backend_co2champion\co2champion_database_app\models.py", line 60, in clean
    if self.target_emissions > (self.start_emissions * 0.8):
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

"POST /api/goal/ HTTP/1.1" 500 166589
